//------------------------------------------------------------------------------
// <auto-generated>
//   This code was generated by a tool.
//
//    Umbraco.ModelsBuilder.Embedded v17.2.0+51e91c8
//
//   Changes to this file will be lost if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Linq.Expressions;
using Umbraco.Cms.Core.Models.PublishedContent;
using Umbraco.Cms.Core.PublishedCache;
using Umbraco.Cms.Infrastructure.ModelsBuilder;
using Umbraco.Cms.Core;
using Umbraco.Extensions;

namespace Umbraco.Cms.Web.Common.PublishedModels
{
	/// <summary>Layout Settings</summary>
	[PublishedModel("layoutSettings")]
	public partial class LayoutSettings : PublishedElementModel, ILayoutSettingsComponentBackgroundImage, ILayoutSettingsComponentColorPicker, ILayoutSettingsComponentContainerStyle
	{
		// helpers
#pragma warning disable 0109 // new is redundant
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "17.2.0+51e91c8")]
		public new const string ModelTypeAlias = "layoutSettings";
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "17.2.0+51e91c8")]
		public new const PublishedItemType ModelItemType = PublishedItemType.Content;
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "17.2.0+51e91c8")]
		[return: global::System.Diagnostics.CodeAnalysis.MaybeNull]
		public new static IPublishedContentType GetModelContentType(IPublishedContentTypeCache contentTypeCache)
			=> PublishedModelUtility.GetModelContentType(contentTypeCache, ModelItemType, ModelTypeAlias);
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "17.2.0+51e91c8")]
		[return: global::System.Diagnostics.CodeAnalysis.MaybeNull]
		public static IPublishedPropertyType GetModelPropertyType<TValue>(IPublishedContentTypeCache contentTypeCache, Expression<Func<LayoutSettings, TValue>> selector)
			=> PublishedModelUtility.GetModelPropertyType(GetModelContentType(contentTypeCache), selector);
#pragma warning restore 0109

		private IPublishedValueFallback _publishedValueFallback;

		// ctor
		public LayoutSettings(IPublishedElement content, IPublishedValueFallback publishedValueFallback)
			: base(content, publishedValueFallback)
		{
			_publishedValueFallback = publishedValueFallback;
		}

		// properties

		///<summary>
		/// Margin Bottom
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "17.2.0+51e91c8")]
		[global::System.Diagnostics.CodeAnalysis.MaybeNull]
		[ImplementPropertyType("marginBottom")]
		public virtual string MarginBottom => this.Value<string>(_publishedValueFallback, "marginBottom");

		///<summary>
		/// Margin Left
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "17.2.0+51e91c8")]
		[global::System.Diagnostics.CodeAnalysis.MaybeNull]
		[ImplementPropertyType("marginLeft")]
		public virtual string MarginLeft => this.Value<string>(_publishedValueFallback, "marginLeft");

		///<summary>
		/// Margin Right
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "17.2.0+51e91c8")]
		[global::System.Diagnostics.CodeAnalysis.MaybeNull]
		[ImplementPropertyType("marginRight")]
		public virtual string MarginRight => this.Value<string>(_publishedValueFallback, "marginRight");

		///<summary>
		/// Margin Top
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "17.2.0+51e91c8")]
		[global::System.Diagnostics.CodeAnalysis.MaybeNull]
		[ImplementPropertyType("marginTop")]
		public virtual string MarginTop => this.Value<string>(_publishedValueFallback, "marginTop");

		///<summary>
		/// Padding Bottom
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "17.2.0+51e91c8")]
		[global::System.Diagnostics.CodeAnalysis.MaybeNull]
		[ImplementPropertyType("paddingBottom")]
		public virtual string PaddingBottom => this.Value<string>(_publishedValueFallback, "paddingBottom");

		///<summary>
		/// Padding Left
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "17.2.0+51e91c8")]
		[global::System.Diagnostics.CodeAnalysis.MaybeNull]
		[ImplementPropertyType("paddingLeft")]
		public virtual string PaddingLeft => this.Value<string>(_publishedValueFallback, "paddingLeft");

		///<summary>
		/// Padding Right
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "17.2.0+51e91c8")]
		[global::System.Diagnostics.CodeAnalysis.MaybeNull]
		[ImplementPropertyType("paddingRight")]
		public virtual string PaddingRight => this.Value<string>(_publishedValueFallback, "paddingRight");

		///<summary>
		/// Padding Top
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "17.2.0+51e91c8")]
		[global::System.Diagnostics.CodeAnalysis.MaybeNull]
		[ImplementPropertyType("paddingTop")]
		public virtual string PaddingTop => this.Value<string>(_publishedValueFallback, "paddingTop");

		///<summary>
		/// Layout Settings Background Image Picker
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "17.2.0+51e91c8")]
		[global::System.Diagnostics.CodeAnalysis.MaybeNull]
		[ImplementPropertyType("layoutSettingsBackgroundImagePicker")]
		public virtual global::Umbraco.Cms.Core.Models.MediaWithCrops LayoutSettingsBackgroundImagePicker => global::Umbraco.Cms.Web.Common.PublishedModels.LayoutSettingsComponentBackgroundImage.GetLayoutSettingsBackgroundImagePicker(this, _publishedValueFallback);

		///<summary>
		/// layoutAreasColourPicker
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "17.2.0+51e91c8")]
		[global::System.Diagnostics.CodeAnalysis.MaybeNull]
		[ImplementPropertyType("layoutAreasColourPicker")]
		public virtual global::Umbraco.Cms.Core.PropertyEditors.ValueConverters.ColorPickerValueConverter.PickedColor LayoutAreasColourPicker => global::Umbraco.Cms.Web.Common.PublishedModels.LayoutSettingsComponentColorPicker.GetLayoutAreasColourPicker(this, _publishedValueFallback);

		///<summary>
		/// Opacity
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "17.2.0+51e91c8")]
		[ImplementPropertyType("layoutSettingsColourOpacity")]
		public virtual decimal LayoutSettingsColourOpacity => global::Umbraco.Cms.Web.Common.PublishedModels.LayoutSettingsComponentColorPicker.GetLayoutSettingsColourOpacity(this, _publishedValueFallback);

		///<summary>
		/// Colour
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "17.2.0+51e91c8")]
		[global::System.Diagnostics.CodeAnalysis.MaybeNull]
		[ImplementPropertyType("layoutSettingsColourPicker")]
		public virtual global::Umbraco.Cms.Core.PropertyEditors.ValueConverters.ColorPickerValueConverter.PickedColor LayoutSettingsColourPicker => global::Umbraco.Cms.Web.Common.PublishedModels.LayoutSettingsComponentColorPicker.GetLayoutSettingsColourPicker(this, _publishedValueFallback);

		///<summary>
		/// Shade
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "17.2.0+51e91c8")]
		[ImplementPropertyType("layoutSettingsColourShades")]
		public virtual decimal LayoutSettingsColourShades => global::Umbraco.Cms.Web.Common.PublishedModels.LayoutSettingsComponentColorPicker.GetLayoutSettingsColourShades(this, _publishedValueFallback);

		///<summary>
		/// Container Style
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "17.2.0+51e91c8")]
		[global::System.Diagnostics.CodeAnalysis.MaybeNull]
		[ImplementPropertyType("containerStyle")]
		public virtual string ContainerStyle => global::Umbraco.Cms.Web.Common.PublishedModels.LayoutSettingsComponentContainerStyle.GetContainerStyle(this, _publishedValueFallback);
	}
}
